  env: "local" // окружение в котором запускают
  storagePath: "./storage/storage/db" // путь до файла в котором будет хранитьс база данных
  http_server:
    address: "Localhost:8082"
    timeOut: 4s // время на чтение запроса и такое же время на отправку ответа
    idleTimeOut: 60s // время жизни соединения клиентом
